### Create a new user
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
 "email":"red@gmail.com",
 "password":"3333"
    
}
### Find a particular user with a given ID
GET http://localhost:4000/auth/1

### Find all users with given email
GET http://localhost:4000/auth?email=red@gmail.com

### delete user with given id
DELETE  http://localhost:4000/auth/1

### Update user
PATCH   http://localhost:4000/auth/3
Content-Type: application/json

{
    "email":"red1@mail.com"
}